apiVersion: v1
kind: ConfigMap
metadata:
  name: yellowbook-config
  namespace: yellowbooks
data:
  NODE_ENV: "production"
  PORT: "3000"
  API_PORT: "3001"
  NEXT_PUBLIC_API_URL: "https://api.yellowbook.yellowbook.testd"