apiVersion: v1
kind: Secret
metadata:
  name: yellowbook-secrets
  namespace: yellowbooks
type: Opaque
stringData:
  DATABASE_URL: "postgresql://yellowbook:lAnBQP9ECM1F38LxHz2ZK65h@postgres-service:5432/yellowbook?schema=public"
  JWT_SECRET: "hZW2pe89CjGXQJTumkqzADiPgEcS4nUY"